### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [whitequark/superlinker#4]
Hi!

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit.

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. Suppose you think that a regular Release build should not be affected by such a change as well. In that case, I suggest adding an additional `dist` or `release-lto` profile where additionally to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. If we enable it on the Cargo profile level, users, who install the application with `cargo install`, will get the LTO-optimized version "automatically". E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48).

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

I have made quick tests (Fedora 40) by adding `lto = true` to the Release profile. The binary size reduction is the following:
* `superlinker`: from 580 Kib to 518 Kib

It's not a big deal, but anyway, you might also consider tweaking other optimization options, like `codegen-units`.

Thank you.

**Comment by whitequark** [comment]
This is spam and I will report it as such.

![Screenshot_20241025_185929](https://github.com/user-attachments/assets/55ca0450-aa95-4de7-8965-e44247085228)

**Comment by berkus** [comment]
Sad, sad state of LTO, why not enable it?

**Comment by berkus** [comment]
Let me elaborate a bit, this is truly [really hard to do](https://github.com/no111u3/tmc5160/blob/0c2670ee2dea10ef9b81f1d89532c5ce8d80d16e/Cargo.toml#L32) - yes, adding A SINGLE LINE. But this advances both your project and understanding of LTO and compiler optimizations in general, and takes literally zero effort to do.

It is even already tested. I may understand if you are not able to perform such arcane optimization yourself. Would you accept a PR?

**Comment by whitequark** [comment]
> I may understand if you are not able to perform such arcane optimization yourself.

Go fuck yourself lmfao. What a piece of shit.
